### ISSUE TITLE
Reporting with AsciiDoc does not render images

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-recorder#15]
When AsciiDoc is chosen as reporter output, AsciiDoc document only contains the path as string of the screenshots but not the image itself so it is pretty much useless.

I will fix this as soon as possible.

**Comment by lordofthejars** [comment]
I have seen that this is because in case of image larger than maxwidth then it is only set the location. I am going to change this to be a link.

**Comment by smiklosovic** [comment]
hi, i was thinking that it is already a line like "file:///path" and it does show as url, it is surprising for me that it just displays a text and that's it. maybe it pays only for html and asciidoc left behind regarding of this

**Comment by lordofthejars** [comment]
Yes i think the bug is on asciidoctor I will check with Dan and close this
issue if required
El dg., 17 de maig, 2015 a les 5.07 Štefan Miklošovič <
notifications@github.com> va escriure:
