### ISSUE TITLE
Move org.arquillian.recorder.reporter.Reportable to SPI

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-recorder#42]
Checking the org.arquillian.recorder.reporter.Reportable class (https://github.com/arquillian/arquillian-recorder/blob/e119c48141538a3e364d4604a67265b9402f07d7/arquillian-recorder-reporter/arquillian-recorder-reporter-api/src/main/java/org/arquillian/recorder/reporter/Reportable.java) is the base class of anything that can be reportable. The thing is that this class has no dependencies to any jar file but it is placed inside `api` module, and this module has a `jaxb` dependency. The problem we are facing now is that we want to create a Cube integration with Recorder, but without having a hard dependency to recorder, so by default from the point of view of Cube you only have a dependency to `recorder-spi` and if user adds manually the recorder dependency then everything is enabled and recorded.

To do this it would be useful to have `Reportable` class in SPI so only one light dependency is on Cube part by default.

WDYT?

**Comment by smiklosovic** [comment]
honestly I am not sure, it sounds like a good idea, try to do that, run tests and see what happens.

**Comment by lordofthejars** [comment]
I will do it tomorrow

El dt., 2 ag. 2016 a les 17:38, Štefan Miklošovič (<notifications@github.com>)
va escriure:
