### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-recorder#46]
@lordofthejars  feel free to release this as you want, there are lot of commits from the last version, ping Aslak if needed and release the kraken :D

**Comment by lordofthejars** [comment]
Well I think template.xsl should be updated too isn t it? Never used xslt
so maybe you can check this in a second to be sure to not miss anything

**Comment by bartoszmajsak** [comment]
Released. Thanks guys!

![triumph-colbert-report](https://cloud.githubusercontent.com/assets/719616/17447259/b99a91ac-5b4d-11e6-87f8-7419383858e0.gif)
